### PR TITLE
Peter Stulpner Tutorial Solution, building package in ROSbuild

### PR DESCRIPTION
**Pull request by peterstulpner**

### CODE REVIEW

**Comment by JmcRobbie** [comment]
Hey, pretty good first attempt, are their ways of using launch file arguments to make the whole thing more concise? 

You should also visualize the whole system in ROS rqt to see that it is working as you expect

**Comment by peterstulpner** [comment]
Hey, cheers haha took a bit of figuring out when you say using launch file arguments do you mean update my current launch file to see if I can make it more concise? I had an idea to have the push nodes as just one node and duplicate in the launch file but I don’t think that makes two topics?

**Comment by JmcRobbie** [comment]
@peterstulpner  https://answers.ros.org/question/277622/roslaunch-command-line-args/ take a look at this for inspiration. Your two publisher nodes are essentially the same except for using different numbers.

**Comment by peterstulpner** [comment]
Awesome cheers, Ill push a new version soon :)

**Review by JmcRobbie — APPROVED** [review]
Nice solution, seem to have understood the core concept and was generally well done.

**Pull request closed without merging**
